on:
  push:
    branches:
      - master

name: CI

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2

      - uses: actions/checkout@v2

      - run: zig build test
      - run: zig build -Doptimize=ReleaseSafe -Dlog-level=debug --summary all
      - run: ./test/run.sh
