on:
  push:
    branches:
      - master

name: CI

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.2284+9b714e019

      - uses: actions/checkout@v2

      - run: zig build test
      - run: zig build -Doptimize=ReleaseSafe --summary all
      - run: ./test/run.sh
